name: Create PDF from README

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://dalibo/pandocker:latest
        with:
          args: "android-introduction.md -o output/android-introduction.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing"
      - uses: actions/upload-artifact@master
        with:
          name: android-introduction.pdf
          path: output
      - uses: docker://dalibo/pandocker:latest
        with:
          args: "import-existing-android-app-to-github.md -o output/import-existing-android-app-to-github.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing"
      - uses: actions/upload-artifact@master
        with:
          name: import-existing-android-app-to-github.pdf
          path: output
      - uses: docker://dalibo/pandocker:latest
        with:
          args: "android-push-notifications.md -o output/android-push-notifications.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing"
      - uses: actions/upload-artifact@master
        with:
          name: android-push-notifications.pdf
          path: output

