name: Create PDF from README

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://jpbernius/pandoc-xelatex:latest
        with: # needs a README in your repo root!
          args: "--standalone --output=output/README.pdf docs/README.md"
      - uses: actions/upload-artifact@master
        with:
          name: readme.pdf
          path: output
      - uses: docker://jpbernius/pandoc-xelatex:latest
        with: # needs a README in your repo root!
          args: "--standalone --output=output/README.docx docs/README.md"
      - uses: actions/upload-artifact@master
        with:
          name: readme.docx
          path: output
