name: Create PDF from README

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          args: "--standalone --output=output/android-introduction-and-assignments.pdf docs/README.md docs/import-existing-android-app-2-github/text.md"
      - uses: actions/upload-artifact@master
        with:
          name: android-introduction-and-assignments.pdf
          path: output
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          args: "--standalone --output=output/android-introduction-and-assignments.docx docs/import-existing-android-app-2-github/text.md"
      - uses: actions/upload-artifact@master
        with:
          name: android-introduction-and-assignments.docx
          path: output
